#!/usr/bin/env bash
# GENERATED by tools/build_hooks.py from bench/clauses.py and register/GYROSCOPE.json.
# Edit those, not this. gate 4 fails if this file stops matching them.
#
# PreToolUse: put the governing clause in front of the model at the moment the command is
# about to run. Plain stdout would reach only the user's transcript, so the reminder is
# returned as additionalContext, with permissionDecision always "allow": this advises, it
# never blocks. A hook that blocks gets disabled, and a disabled hook fires never.
set -euo pipefail
payload=$(cat)
command=$(printf '%s' "$payload" | python3 -c 'import json,sys;d=json.load(sys.stdin);print((d.get("tool_input") or {}).get("command",""))' 2>/dev/null || true)
[ -z "$command" ] && exit 0
hits=''
add() { hits="${hits}${hits:+$'\n'}$1"; }

if printf '%s' "$command" | grep -Eq -- '\bfind\b.*-delete|\bfind\b.*-exec[[:space:]]+rm|\brm[[:space:]]+-[a-zA-Z]*r'; then
  add 'U17: run the selector with -print and diff it against what you expect'
fi
if printf '%s' "$command" | grep -Eq -- '--apply\b'; then
  add 'U20: run it without --apply, then verify one condemned item by hand — the tool'\''s own verdict does not count'
fi
if printf '%s' "$command" | grep -Eq -- '\bgit\b.*\bcommit\b.*(-S\b|--gpg-sign)'; then
  add 'U08: empty signed canary commit first; signer fails => stop, never unsign'
fi
if printf '%s' "$command" | grep -Eq -- 'track\.sh\b.*--pid|--host-pid\b'; then
  add 'U03: observe it from the consumer'\''s side first'
fi
if printf '%s' "$command" | grep -Eq -- '\b(pytest|unittest|npm test|go test|cargo test|make test|tox)\b'; then
  add 'C16-warnings-are-errors: rerun once with warnings promoted to errors; a warning is a red, not a footnote'
fi
if printf '%s' "$command" | grep -Eq -- '\b(pytest|unittest)\b.*\b(tests?/[A-Za-z0-9_./-]*new|plant)\b'; then
  add 'C05-watch-it-fail: plant a fault and watch the check go red'
fi
if printf '%s' "$command" | grep -Eq -- '\b(wc -l|grep -c|--count|\| *wc\b|ls .*\| *wc)\b'; then
  add 'C07-count-at-head: name the revision and recount there; a mismatch is the finding'
fi
if printf '%s' "$command" | grep -Eq -- '\b(pgrep|pkill|ps -[a-z]|ps a[a-z])\b'; then
  add 'C09-checker-excludes-self: exclude your own pid by identity, not by pattern'
fi
if printf '%s' "$command" | grep -Eq -- '\bgit (commit|push)\b'; then
  add 'C11-uncommitted-unfinished: run the final status; dirty is unfinished'
fi
if printf '%s' "$command" | grep -Eq -- '\b(pkill|kill -|killall)\b'; then
  add 'C13-stop-verified-by-gone: list what is gone, including what you started'
fi
if printf '%s' "$command" | grep -Eq -- '\b(codex|dispatch\.sh|claude -p)\b'; then
  add 'C03-verify-what-returns: read the artifact it returned'
fi
if printf '%s' "$command" | grep -Eq -- '\b(codex|dispatch\.sh|claude -p)\b'; then
  add 'U01: probe one child for home, transport, and result write'
fi
if printf '%s' "$command" | grep -Eq -- '\b(codex|dispatch\.sh|claude -p)\b'; then
  add 'U02: probe that the failed precondition actually changed'
fi
if printf '%s' "$command" | grep -Eq -- '\bchecker\b|\bcheck\.(py|sh)\b'; then
  add 'C08-check-can-fail: remove the input and confirm it fails'
fi
if printf '%s' "$command" | grep -Eq -- '\btouch[[:space:]]+[A-Za-z0-9_./-]+\.(py|sh)\b|(^|[^>])>[[:space:]]*[A-Za-z0-9_./-]+\.(py|sh)\b'; then
  add 'C15-one-job-per-name: search for an existing owner first'
fi

[ -z "$hits" ] && exit 0
python3 - "$hits" <<'PY'
import json, sys
hits = sys.argv[1]
print(json.dumps({"hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    # No permissionDecision. "allow" does not mean "do not block" -- it AUTO-APPROVES,
    # suppressing the prompt the user would otherwise see, and these patterns match rm -r,
    # find -delete, pkill and git push. A caution hook that silently grants permission for
    # the calls it cautions about is the exact defect this skill is about. Omitting the
    # field leaves the permission flow untouched; additionalContext is delivered anyway.
    "additionalContext": "Gyroscope — one cheap call first, then cite it:\n" + hits,
}}))
PY
