#!/usr/bin/env bash
# GENERATED by tools/build_hooks.py.
#
# SessionStart: stdout is added to the model's context, so this is the arm that covers all
# 21 rows -- including the six whose occasion is a mid-task judgement no command reveals
# and no prompt contains. It is why the guarantee does not rest on description matching.
#
# The slice is keyed on the generated-block markers, not on prose headings: headings are
# edited freely and a renamed one would silently truncate this to nothing or to the whole
# file. It carries the rule and the map only -- the exclusion table and the bench
# provenance are auditor's material, and context spent every session on them is context
# a reader pays for and cannot use.
set -euo pipefail
if [ -n "${GYROSCOPE_STATE_DIR:-}" ]; then
  new_state="$GYROSCOPE_STATE_DIR"
  old_state="$(dirname "$new_state")/asymmetry_state"
elif [ -n "${CODEX_PLUGIN_ROOT:-}" ] || [ -n "${CODEX_HOME:-}" ]; then
  new_state="$HOME/.codex/gyroscope_state"
  old_state="$HOME/.codex/asymmetry_state"
else
  new_state="$HOME/.claude/gyroscope_state"
  old_state="$HOME/.claude/asymmetry_state"
fi
if [ -d "$old_state" ] && [ ! -e "$new_state" ]; then
  printf '%s\n' "GYROSCOPE STARTUP REFUSED: legacy state directory exists at $old_state; hard rename requires an explicit state migration to $new_state" >&2
  exit 78
fi
skill="${GYROSCOPE_SKILL:-$HOME/.claude/skills/gyroscope/SKILL.md}"
[ -f "$skill" ] || exit 0
awk '
  /^# Gyroscope/      { on = 1 }
  /BEGIN GENERATED/   { inblock = 1; next }
  /## Not shipped/    { inblock = 0; on = 0 }
  on && !inblock      { print; next }
  inblock             { print }
' "$skill"
